### ISSUE TITLE
Create Migration Files

### ISSUE THREAD

**Issue by aungminzan** [aungminzan/Blog#1]
## Description
Create migration files for admins, users, posts and comments tables.

## Task list
- [x] Create migration files for admins table.
- [x] Create migration files for users table.
- [x] Create migration files for posts table.
- [x] Create migration files for comments table.
